### ISSUE TITLE
Error when no Endpoint details are specified

### ISSUE THREAD

**Issue by z-mani** [terrablocks/aws-sftp-server#6]
I seem to be getting an error when defining a SELF MANAGED, PUBLIC facing SFTP Server.

The error I'm getting is;

│ Error: Invalid function argument
│ 
│   on .terraform/modules/sftp/main.tf line 100, in resource "aws_security_group" "sftp_vpc":
│  100:   count       = var.sftp_type == "VPC" && length(lookup(var.endpoint_details, "security_group_ids", [])) == 0 ? 1 : 0
│     ├────────────────
│     │ var.endpoint_details is null
│ 
│ Invalid value for "inputMap" parameter: argument must not be null.

It shouldn't be throwing this error as it is not a required field if we aren't using VPC_ENDPOINT? Or am I missing something?

I am using SFTP Server

Thanks

**Comment by paliwalvimal** [comment]
@z-mani Please share the piece of code to analyse

**Comment by z-mani** [comment]
The code for the sftp module is in my main.tf file;

```
module "sftp" {
  source    = "github.com/terrablocks/aws-sftp-server.git"

  name                   = var.sftp_server_name
  force_destroy          = true 
  host_key               = var.ssh_private_host_key
  sftp_users             = var.sftp_users
  sftp_users_ssh_key     = var.sftp_users_ssh_key
}
```

**Comment by paliwalvimal** [comment]
@z-mani Thanks for raising the issue. It has now been fixed. Feel free to write back in case you are still facing issue with the module

**Comment by z-mani** [comment]
Hi @paliwalvimal, thanks for fixing the issue. Another issue is now arising when I apply. Please see below;

```
╷
│ Error: error creating Transfer Server: InvalidRequestException: Invalid host key format
│ 
│   with module.sftp.aws_transfer_server.public[0],
│   on .terraform/modules/sftp/main.tf line 97, in resource "aws_transfer_server" "public":
│   97: resource "aws_transfer_server" "public" {
│ 
╵
Releasing state lock. This may take a few moments...
```

Seems the key pairing is off in the new public resource that has been added?

**Comment by paliwalvimal** [comment]
@z-mani This error is raised by the AWS provider. Please make sure to pass the host key is correct format. I tested it myself and was able to launch a PUBLIC SFTP server with a host key

**Comment by z-mani** [comment]
@paliwalvimal I have created the key using `ssh-keygen -t rsa -b 2048 -N "" -m PEM -f my-new-server-key` and copied the whole key but still shows error? Also does your module support attaching an S3 bucket? Thanks

**Comment by paliwalvimal** [comment]
@z-mani As I mentioned earlier as well this is not module specific error and is raised by Terraform AWS provider. If you feel there's a bug please raise it with Terraform team.

Yes, you can associate S3 bucket with SFTP server. Please refer to the readme.

**Comment by z-mani** [comment]
@paliwalvimal Thanks for the reply. I have looked at readme but there is no mention of S3 bucket let alone attaching a bucket to the server unless I am overlooking it. Could you please point to me where it is?
Thanks

**Comment by paliwalvimal** [comment]
@z-mani I have update the readme to include how to map S3 to the user. Please refer to the `sftp_users` variable in the updated readme.
