### ISSUE TITLE
[Bug] Subnet_ids invalid

### ISSUE THREAD

**Issue by bilalsiddique98** [terrablocks/aws-sftp-server#8]
### Prerequisites

- [X] I am running the latest version
- [X] I read the documentation properly and found no answer
- [X] I have checked to make sure that this issue has not already been filed

### Expected Behavior

Take the subnet_ids as expected

### Current Behavior

│ Error: Invalid function argument
│
│   on transfer.tf line 89, in resource "aws_eip" "sftp_vpc":
│   89:   count = var.sftp_type == "VPC" && lookup(var.endpoint_details, "address_allocation_ids", null) == null ? length(lookup(var.endpoint_details, var.subnet_ids[0])) : 0
│     ├────────────────
│     │ var.endpoint_details is object with 4 attributes
│
│ Invalid value for "inputMap" parameter: the given object has no attribute "subnet-XXXXXXXXXXXX".

### Steps To Reproduce

with this config:
resource "aws_eip" "sftp_vpc" {
  count = var.sftp_type == "VPC" && lookup(var.endpoint_details, "address_allocation_ids", null) == null ? length(lookup(var.endpoint_details, var.subnet_ids[0])) : 0
  vpc   = true
  tags  = var.tags
}

resource "aws_transfer_server" "vpc" {
  count         = var.sftp_type != "PUBLIC" ? 1 : 0
  endpoint_type = var.sftp_type
  protocols     = var.protocols
  certificate   = var.certificate_arn

  endpoint_details {
    vpc_id                 = lookup(var.endpoint_details, var.vpc_id, null)
    # vpc_endpoint_id        = lookup(var.endpoint_details, "vpc_endpoint_id", null)
    subnet_ids             = lookup(var.endpoint_details, var.subnet_ids[0], null)
    security_group_ids     = lookup(var.endpoint_details, "security_group_ids", aws_security_group.sftp_vpc.*.id)
    address_allocation_ids = lookup(var.endpoint_details, "address_allocation_ids", aws_eip.sftp_vpc.*.allocation_id)
  }

  identity_provider_type = var.identity_provider_type
  url                    = var.api_gw_url
  invocation_role        = var.invocation_role
  directory_id           = var.directory_id
  function               = var.function_arn

  logging_role         = var.logging_role == null ? join(",", aws_iam_role.logging.*.arn) : var.logging_role
  force_destroy        = var.force_destroy
  security_policy_name = var.security_policy_name
  host_key             = var.host_key

   tags = merge({
     Name = local.name
   }, var.tags)
}

Note:
Had to also comment out endpoint_details, because it was giving me null errors. Trying to create SFTP server VPC and internet facing.

### Environment

```markdown
- Operating System: WSL Ubuntu
- Terraform Version: Terraform v1.0.10
- Provider version:
- Module Version:
```

**Comment by bilalsiddique98** [comment]
Solved

**Comment by paliwalvimal** [comment]
@bilalsiddique98 Looking at the error code it seems like you are not using the latest version of this module
